Feature/speech prediction
ScazLab/baxter_collaboration pull request #57
Opened 2017-07-18 18:03 UTC by JakeBrawer

Created  web interface for human collaboration speech prediction project.

2017-07-18 18:35 UTC, alecive requested changes
The main thing you should change is filenames (to match the containing folder).

2017-07-18 18:35 UTC, alecive commented on human_robot_collaboration/launch/flatpack_furniture.launch
> +    </rosparam>
Why did you have to modify this file? Please revert.

2017-07-18 18:35 UTC, alecive commented on human_robot_collaboration/launch/speech_prediction.launch
> -<launch>
So this file is not needed any more?

2017-07-18 18:35 UTC, alecive commented on human_robot_collaboration/web-interface/speech_predicition/interface.html
> + <!DOCTYPE html>
added useless space

2017-07-18 18:35 UTC, alecive commented on human_robot_collaboration/web-interface/speech_predicition/interface.html
> +                    <svg> </svg>
useless space?

2017-07-18 18:35 UTC, alecive commented on human_robot_collaboration/web-interface/speech_predicition/interface.html
> +        aC
this is definitely not needed.

2017-07-18 18:35 UTC, alecive commented on human_robot_collaboration/web-interface/speech_predicition/ros.js
> +  messageType : 'baxter_collaboration_msgs/DoAction'
revert back to `human_robot_collaboration_msgs`

2017-07-18 18:35 UTC, alecive commented on human_robot_collaboration/web-interface/speech_predicition/ros.js
> +  messageType : 'baxter_collaboration_msgs/DoAction'
revert back to `human_robot_collaboration_msgs`

2017-07-18 18:35 UTC, alecive commented on human_robot_collaboration/web-interface/speech_predicition/ros.js
> +
useless space

2017-07-18 18:35 UTC, alecive commented on human_robot_collaboration/web-interface/speech_predicition/style.css
> +t
not needed.

2017-07-18 18:35 UTC, alecive commented on human_robot_collaboration/web-interface/speech_predicition/tables.js
> +        .text("STATE: " + msg.state);
alignment

2017-07-18 18:35 UTC, alecive commented on human_robot_collaboration/web-interface/speech_predicition/tables.js
> +        .text("ACTION: " + msg.action);
alignment

2017-07-18 18:35 UTC, alecive commented on human_robot_collaboration/web-interface/speech_predicition/tables.js
> +        .text("OBJECT: " + msg.object);
alignment

2017-07-18 18:35 UTC, alecive commented on human_robot_collaboration_lib/src/robot_perception/cartesian_estimator.cpp
> +
useless space

2017-07-18 18:35 UTC, alecive commented on human_robot_collaboration_lib/src/robot_perception/cartesian_estimator.cpp
> +            geometry_msgs::Point cent;
indentation

2017-07-19 15:53 UTC, JakeBrawer commented on human_robot_collaboration/launch/flatpack_furniture.launch
> +    </rosparam>
I didnt mean too, sorry

2017-07-19 15:55 UTC, JakeBrawer commented on human_robot_collaboration/web-interface/speech_predicition/interface.html
> +        aC
This is the command for opening up slack in emacs:^)

2017-07-19 16:10 UTC, alecive commented on human_robot_collaboration/web-interface/speech_predicition/ros.js
> +            var res = new ROSLIB.ServiceResponse();
@houndci-bot has a point. We should define `req` and `res` once in the beginning, and reuse them later on.

2017-07-19 16:11 UTC, alecive requested changes

2017-07-19 16:11 UTC, alecive commented on human_robot_collaboration/launch/flatpack_furniture.launch
> -    <node pkg="human_robot_collaboration" type="flatpack_action_provider" name="flatpack_action_provider" output="screen"/>
You still have this to be taken care of.

2017-07-19 16:11 UTC, alecive commented on human_robot_collaboration/launch/speech_prediction.launch
> +        "screwdriver"    : 1
indentation

2017-07-19 17:23 UTC, alecive approved these changes

2017-07-19 17:27 UTC, merged